Repository GreenMeteor/verified, pull requests merged in 2023-04, with the labels that each got.

#3 Enh: Implement space settings
  Module.php
  docs/CHANGELOG.md
  models/ConfigureForm.php
  module.json
  views/admin/index.php
  widgets/ContainerProfileHeaderOverwrite.php
Labels: Meta: New Version, Status: TBA, Type: Enh

#12 Use primary color as default
  models/ConfigureForm.php
Labels: Type: Enh

#9 Enh: Show mark in stream entries and comments
  Events.php
  Module.php
  config.php
  docs/CHANGELOG.md
  docs/DEVELOPER.md
  docs/README.md
  messages/de/base.php
  module.json
  widgets/ContainerProfileHeaderOverwrite.php
  widgets/PeopleCardOverwrite.php
  widgets/SpaceDirectoryCardOverwrite.php
  widgets/VerifiedComment.php
  widgets/VerifiedIcon.php
  widgets/VerifiedPeopleCard.php
  widgets/VerifiedProfileHeader.php
  widgets/VerifiedSpaceCard.php
  widgets/views/comment.php
  widgets/views/containerProfileHeader.php
  widgets/views/peopleCard.php
  widgets/views/spaceDirectoryCard.php
  widgets/views/wallStreamEntryHeader.php
Labels: Meta: New Version, Type: Enh

#16 Fix maxnumber
  Module.php
  docs/CHANGELOG.md
  migrations/m230422_062254_maxNumber_to_maxUsers.php
  models/ConfigureForm.php
  views/admin/index.php
Labels: Type: Enh
